# Generated by Django 3.2 on 2021-12-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0002_alter_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
