# Generated by Django 3.2 on 2021-12-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0005_alter_packagecheckout_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecheckout',
            name='discount',
        ),
    ]
