# Generated by Django 3.2 on 2021-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0007_auto_20211205_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecheckout',
            name='shop',
        ),
        migrations.AddField(
            model_name='packagecheckout',
            name='shop_logo_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='packagecheckout',
            name='shop_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
