# Generated by Django 3.2 on 2021-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0008_auto_20211205_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecheckout',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
