# Generated by Django 3.2.9 on 2021-12-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0011_shop_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecheckout',
            name='customer_email',
        ),
    ]
