# Generated by Django 3.2.9 on 2021-12-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0013_packagecheckout_customer_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagecheckout',
            name='shop_logo_img',
        ),
        migrations.RemoveField(
            model_name='packagecheckout',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='packagecheckout',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAS.shop'),
        ),
    ]
