# Generated by Django 3.2.9 on 2021-12-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0015_packagecheckout_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecheckout',
            name='is_expired',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
