# Generated by Django 3.2 on 2021-11-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
