# Generated by Django 3.2 on 2021-11-30 08:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restcheckout',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='due',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='total',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='type',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='vat',
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer'),
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='items',
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.item'),
        ),
    ]
