# Generated by Django 3.2 on 2021-12-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20211130_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restcheckout',
            name='items',
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='items',
            field=models.ManyToManyField(null=True, to='restaurant.Item'),
        ),
    ]
