# Generated by Django 3.2 on 2021-12-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20211202_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcheckout',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
