# Generated by Django 3.2 on 2021-12-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_customer_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.IntegerField(null=True),
        ),
    ]
