# Generated by Django 3.2 on 2021-12-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_vendor_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_descriptions',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
