# Generated by Django 3.2 on 2021-12-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_alter_item_product_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
