# Generated by Django 3.2 on 2021-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_item_buying_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='upc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
