# Generated by Django 3.2 on 2021-12-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_restcheckout_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restcheckout',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
