# Generated by Django 3.2 on 2021-12-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_alter_restcheckout_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restcheckout',
            name='items',
            field=models.ManyToManyField(to='restaurant.CartItems'),
        ),
    ]
