# Generated by Django 3.2 on 2021-12-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_alter_restcheckout_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='duemodel',
            name='due_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
