# Generated by Django 3.2 on 2021-12-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_auto_20211204_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcheckout',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], max_length=255, null=True),
        ),
    ]
