# Generated by Django 3.2 on 2021-12-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_vendor_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='out_of_stock',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
