# Generated by Django 3.2.9 on 2021-12-07 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0015_packagecheckout_due_date'),
        ('restaurant', '0031_alter_item_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAS.shop'),
        ),
    ]
