# Generated by Django 3.2.9 on 2021-12-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_table_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecheckout',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tablecheckout',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tablecheckout',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tablecheckout',
            name='table_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
