# Generated by Django 3.2.9 on 2021-12-07 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAAS', '0016_packagecheckout_is_expired'),
        ('restaurant', '0033_auto_20211207_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecheckout',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SAAS.shop'),
        ),
    ]
