# Generated by Django 3.2.9 on 2021-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_tablecheckout_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='restcheckout',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='restcheckout',
            name='nagad_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
