# Generated by Django 3.2.9 on 2021-12-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_auto_20211207_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restcheckout',
            old_name='bkash_number',
            new_name='payment_number',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='restcheckout',
            name='nagad_number',
        ),
    ]
