# Generated by Django 3.2.9 on 2021-12-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0039_category_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
    ]
